CREATE TABLE teams (
  id VARCHAR(26) PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  manager_id VARCHAR(26) REFERENCES employees(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  deleted_at TIMESTAMPTZ NULL
);