// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: employees.sql

package models

import (
	"context"
)

const addEmployee = `-- name: AddEmployee :one
INSERT INTO employees (id, name, email, password, phone, role_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, email, password, phone, role_id, team_id, manager_id, created_at, updated_at, deleted_at
`

type AddEmployeeParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
	RoleID   string `json:"roleId"`
}

func (q *Queries) AddEmployee(ctx context.Context, arg AddEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, addEmployee,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.RoleID,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.RoleID,
		&i.TeamID,
		&i.ManagerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEmployeeByEmail = `-- name: GetEmployeeByEmail :one
SELECT id, name, email, password, phone, role_id, team_id, manager_id, created_at, updated_at, deleted_at FROM employees WHERE email = $1
`

func (q *Queries) GetEmployeeByEmail(ctx context.Context, email string) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByEmail, email)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.RoleID,
		&i.TeamID,
		&i.ManagerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEmployeeById = `-- name: GetEmployeeById :one
SELECT id, name, email, password, phone, role_id, team_id, manager_id, created_at, updated_at, deleted_at FROM employees WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEmployeeById(ctx context.Context, id string) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeById, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.RoleID,
		&i.TeamID,
		&i.ManagerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEmployeesByIds = `-- name: GetEmployeesByIds :many
SELECT id, name, email, password, phone, role_id, team_id, manager_id, created_at, updated_at, deleted_at FROM employees WHERE id = ANY($1::VARCHAR[]) AND deleted_at IS NULL
`

func (q *Queries) GetEmployeesByIds(ctx context.Context, id []string) ([]Employee, error) {
	rows, err := q.db.Query(ctx, getEmployeesByIds, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Phone,
			&i.RoleID,
			&i.TeamID,
			&i.ManagerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleIdById = `-- name: GetRoleIdById :one
SELECT role_id FROM employees WHERE id = $1
`

func (q *Queries) GetRoleIdById(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getRoleIdById, id)
	var role_id string
	err := row.Scan(&role_id)
	return role_id, err
}

const listUEmployees = `-- name: ListUEmployees :many
SELECT id, name, email, password, phone, role_id, team_id, manager_id, created_at, updated_at, deleted_at FROM employees ORDER BY created_at DESC
`

func (q *Queries) ListUEmployees(ctx context.Context) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listUEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Phone,
			&i.RoleID,
			&i.TeamID,
			&i.ManagerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
