// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"database/sql"

	"github.com/jackc/pgtype"
)

type Customer struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	Phone     string       `json:"phone"`
	CreatedAt sql.NullTime `json:"createdAt"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
	DeletedAt sql.NullTime `json:"deletedAt"`
}

type Employee struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Phone     string         `json:"phone"`
	RoleID    string         `json:"roleId"`
	TeamID    sql.NullString `json:"teamId"`
	ManagerID sql.NullString `json:"managerId"`
	CreatedAt sql.NullTime   `json:"createdAt"`
	UpdatedAt sql.NullTime   `json:"updatedAt"`
	DeletedAt sql.NullTime   `json:"deletedAt"`
}

type Permission struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Object string `json:"object"`
	Action string `json:"action"`
}

type Role struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type RolePermission struct {
	RoleID       string `json:"roleId"`
	PermissionID string `json:"permissionId"`
}

type Team struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	ManagerID sql.NullString `json:"managerId"`
	CreatedAt sql.NullTime   `json:"createdAt"`
	UpdatedAt sql.NullTime   `json:"updatedAt"`
	DeletedAt sql.NullTime   `json:"deletedAt"`
}

type Ticket struct {
	ID            string         `json:"id"`
	CreatedBy     string         `json:"createdBy"`
	CreatedByType sql.NullString `json:"createdByType"`
	AssignedTo    sql.NullString `json:"assignedTo"`
	TeamID        sql.NullString `json:"teamId"`
	Category      []string       `json:"category"`
	Priority      string         `json:"priority"`
	Status        string         `json:"status"`
	Tags          []string       `json:"tags"`
	ResponseTime  sql.NullInt64  `json:"responseTime"`
	Watchers      pgtype.JSONB   `json:"watchers"`
	CreatedAt     sql.NullTime   `json:"createdAt"`
	UpdatedAt     sql.NullTime   `json:"updatedAt"`
	DeletedAt     sql.NullTime   `json:"deletedAt"`
}

type TicketAttachment struct {
	ID           string         `json:"id"`
	TicketID     sql.NullString `json:"ticketId"`
	FileUrl      sql.NullString `json:"fileUrl"`
	UploadedBy   string         `json:"uploadedBy"`
	UploaderType sql.NullString `json:"uploaderType"`
	CreatedAt    sql.NullTime   `json:"createdAt"`
	UpdatedAt    sql.NullTime   `json:"updatedAt"`
	DeletedAt    sql.NullTime   `json:"deletedAt"`
}
