// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: permissions.sql

package models

import (
	"context"
)

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (id, name, object, action) VALUES ($1, $2, $3, $4)
RETURNING id, name, object, action
`

type CreatePermissionParams struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Object string `json:"object"`
	Action string `json:"action"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission,
		arg.ID,
		arg.Name,
		arg.Object,
		arg.Action,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Object,
		&i.Action,
	)
	return i, err
}

const getAllPermissions = `-- name: GetAllPermissions :many
SELECT id, name, object, action FROM permissions ORDER BY id ASC
`

func (q *Queries) GetAllPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Object,
			&i.Action,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionByName = `-- name: GetPermissionByName :one
SELECT id, name, object, action FROM permissions WHERE name = $1
`

func (q *Queries) GetPermissionByName(ctx context.Context, name string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByName, name)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Object,
		&i.Action,
	)
	return i, err
}

const getPermissionsByUserID = `-- name: GetPermissionsByUserID :many
SELECT p.object, p.action 
FROM permissions p
JOIN role_permissions rp ON p.id = rp.id
JOIN roles r ON rp.id = r.role_id
JOIN employees e ON e.role_id = r.role_id
WHERE e.id = $1
`

type GetPermissionsByUserIDRow struct {
	Object string `json:"object"`
	Action string `json:"action"`
}

func (q *Queries) GetPermissionsByUserID(ctx context.Context, id string) ([]GetPermissionsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getPermissionsByUserID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPermissionsByUserIDRow{}
	for rows.Next() {
		var i GetPermissionsByUserIDRow
		if err := rows.Scan(&i.Object, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasPermission = `-- name: HasPermission :one
SELECT EXISTS (
  SELECT 1 FROM role_permissions rp
  JOIN permissions p ON rp.permission_id = p.id
  WHERE rp.role_id = $1
  AND p.object = $2 
  AND p.action = $3
)
`

type HasPermissionParams struct {
	RoleID string `json:"roleId"`
	Object string `json:"object"`
	Action string `json:"action"`
}

func (q *Queries) HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPermission, arg.RoleID, arg.Object, arg.Action)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertPermissions = `-- name: InsertPermissions :one
INSERT INTO permissions (id, name, object, action) VALUES ($1, $2, $3, $4)
RETURNING id, name, object, action
`

type InsertPermissionsParams struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Object string `json:"object"`
	Action string `json:"action"`
}

func (q *Queries) InsertPermissions(ctx context.Context, arg InsertPermissionsParams) (Permission, error) {
	row := q.db.QueryRow(ctx, insertPermissions,
		arg.ID,
		arg.Name,
		arg.Object,
		arg.Action,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Object,
		&i.Action,
	)
	return i, err
}
