// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: teams.sql

package models

import (
	"context"
	"database/sql"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, name, manager_id)
VALUES ($1, $2, $3)
RETURNING id, name, manager_id, created_at, updated_at, deleted_at
`

type CreateTeamParams struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	ManagerID sql.NullString `json:"managerId"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.ID, arg.Name, arg.ManagerID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ManagerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTeamById = `-- name: GetTeamById :one
SELECT id, name, manager_id, created_at, updated_at, deleted_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeamById(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamById, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ManagerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
