// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ticket_attachments.sql

package models

import (
	"context"
	"database/sql"
)

const getTicketAttachmentByID = `-- name: GetTicketAttachmentByID :one
SELECT id, ticket_id, file_url, uploaded_by, uploader_type, created_at, updated_at, deleted_at FROM ticket_attachments WHERE id = $1
`

func (q *Queries) GetTicketAttachmentByID(ctx context.Context, id string) (TicketAttachment, error) {
	row := q.db.QueryRow(ctx, getTicketAttachmentByID, id)
	var i TicketAttachment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.FileUrl,
		&i.UploadedBy,
		&i.UploaderType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertTicketAttachment = `-- name: InsertTicketAttachment :one
INSERT INTO ticket_attachments (id, ticket_id, file_url, uploaded_by, uploader_type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ticket_id, file_url, uploaded_by, uploader_type, created_at, updated_at, deleted_at
`

type InsertTicketAttachmentParams struct {
	ID           string         `json:"id"`
	TicketID     sql.NullString `json:"ticketId"`
	FileUrl      sql.NullString `json:"fileUrl"`
	UploadedBy   string         `json:"uploadedBy"`
	UploaderType sql.NullString `json:"uploaderType"`
}

func (q *Queries) InsertTicketAttachment(ctx context.Context, arg InsertTicketAttachmentParams) (TicketAttachment, error) {
	row := q.db.QueryRow(ctx, insertTicketAttachment,
		arg.ID,
		arg.TicketID,
		arg.FileUrl,
		arg.UploadedBy,
		arg.UploaderType,
	)
	var i TicketAttachment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.FileUrl,
		&i.UploadedBy,
		&i.UploaderType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTickeAttachmentFileUrl = `-- name: UpdateTickeAttachmentFileUrl :exec
UPDATE ticket_attachments
SET file_url = $1,
    updated_at = Now()
WHERE id = $2
`

type UpdateTickeAttachmentFileUrlParams struct {
	FileUrl sql.NullString `json:"fileUrl"`
	ID      string         `json:"id"`
}

func (q *Queries) UpdateTickeAttachmentFileUrl(ctx context.Context, arg UpdateTickeAttachmentFileUrlParams) error {
	_, err := q.db.Exec(ctx, updateTickeAttachmentFileUrl, arg.FileUrl, arg.ID)
	return err
}
